version: "3.8"

networks:
  fabric_net:
    driver: bridge

volumes:
  peer0-org1-data:

services:
  peer0_org1:
    image: hyperledger/fabric-peer:2.5
    platform: linux/amd64
    container_name: peer0.org1.example.com
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - FABRIC_LOGGING_SPEC=INFO
    volumes:
      - ./configs/peer0-org1/msp:/etc/hyperledger/fabric/msp
      - peer0-org1-data:/var/hyperledger/production
    ports:
      - "7051:7051"
    networks:
      - fabric_net

  orderer:
    image: hyperledger/fabric-orderer:2.5
    platform: linux/amd64
    container_name: orderer.example.com
    environment:
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - FABRIC_LOGGING_SPEC=INFO
    volumes:
      - ./configs/orderer/msp:/var/hyperledger/orderer/msp
      - ./configs/orderer/genesis.block:/var/hyperledger/orderer/genesis.block
    ports:
      - "7050:7050"
    networks:
      - fabric_net